# Generated by Django 5.2.3 on 2025-07-17 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TodoApp', '0003_profile_task_delete_signup'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='time_scheduled',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='completed_tasks',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='profile',
            name='pending_tasks',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='profile',
            name='total_tasks',
            field=models.IntegerField(default=0),
        ),
    ]
