# Generated by Django 5.2.3 on 2025-07-12 14:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_school'),
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolStudent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=100)),
                ('school_attended', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student', to='product.school')),
            ],
        ),
    ]
