# Generated by Django 5.2.4 on 2025-10-03 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SimpleBlog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='post_images',
            field=models.ImageField(blank=True, null=True, upload_to='post-pics/'),
        ),
    ]
