# Generated by Django 5.2.4 on 2025-10-03 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SimpleBlog', '0002_post_post_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_images',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
