# Generated by Django 5.2.3 on 2025-07-07 10:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GameSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_status', models.CharField(default='waiting', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_word', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Word_Chain_player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_name', models.CharField(max_length=100)),
                ('player_status', models.CharField(default='waiting', max_length=10)),
                ('player_turn_order', models.IntegerField(default=0)),
                ('game_session_joined', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='players', to='Games.gamesession')),
            ],
        ),
        migrations.AddField(
            model_name='gamesession',
            name='current_player',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Games.word_chain_player'),
        ),
        migrations.AddField(
            model_name='gamesession',
            name='winner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='winner', to='Games.word_chain_player'),
        ),
        migrations.CreateModel(
            name='Word_Chain_words',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word_provided', models.CharField(max_length=100)),
                ('word_used_already', models.CharField(max_length=100)),
                ('player_who_provided', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='words_provided', to='Games.word_chain_player')),
                ('word_game_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='words_used', to='Games.gamesession')),
            ],
        ),
    ]
