# Generated by Django 5.2.3 on 2025-07-07 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Games', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='word_chain_words',
            name='word_used_already',
            field=models.BooleanField(default=False),
        ),
    ]
